[mouse]

[cursor]
blink_interval = 750

[cursor.style]
blinking = "on"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.offset]
x = 0    # For letter spacing (default: 0).
y = 0    # For line spacing (default: 0).

[font.normal]
family = "JetBrainsMonoNLNerdFont"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[scrolling]
history = 2000
multiplier = 3

[terminal.shell]
program = "/usr/bin/zsh"

[window]
decorations = "Buttonless"
dynamic_title = true
opacity = 1.0
dynamic_padding = true

[window.padding]
x = 4
y = 4

[general]
import = [
    # "~/.config/alacritty/themes/themes/everforest_dark.toml"
    # "~/.config/alacritty/themes/themes/kanagawa_wave.toml"
    "~/.config/alacritty/themes/themes/gruvbox_material.toml"
]

# Default colors
# [colors.primary]
# background = '#000000'
# foreground = '#d4be98'
#
# # Normal colors
# [colors.normal]
# black   = '#3c3836'
# red     = '#ea6962'
# green   = '#a9b665'
# yellow  = '#d8a657'
# blue    = '#7daea3'
# magenta = '#d3869b'
# cyan    = '#89b482'
# white   = '#d4be98'
#
# # Bright colors (same as normal colors)
# [colors.bright]
# black   = '#3c3836'
# red     = '#ea6962'
# green   = '#a9b665'
# yellow  = '#d8a657'
# blue    = '#7daea3'
# magenta = '#d3869b'
# cyan    = '#89b482'
# white   = '#d4be98'
#
